# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='image.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0bimage.proto\":\n\x05image\x12\r\n\x05width\x18\x01 \x02(\x05\x12\x0e\n\x06height\x18\x02 \x02(\x05\x12\x12\n\nimage_data\x18\x03 \x02(\x0c\"\x14\n\x07\x64\x65pth_m\x12\t\n\x01\x64\x18\x01 \x02(\x02\"5\n\x03vel\x12\n\n\x02vx\x18\x01 \x02(\x02\x12\n\n\x02vy\x18\x02 \x02(\x02\x12\n\n\x02vz\x18\x03 \x02(\x02\x12\n\n\x02rz\x18\x04 \x02(\x02')
)




_IMAGE = _descriptor.Descriptor(
  name='image',
  full_name='image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='image.width', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='image.height', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_data', full_name='image.image_data', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=73,
)


_DEPTH_M = _descriptor.Descriptor(
  name='depth_m',
  full_name='depth_m',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='d', full_name='depth_m.d', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=95,
)


_VEL = _descriptor.Descriptor(
  name='vel',
  full_name='vel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vx', full_name='vel.vx', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vy', full_name='vel.vy', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vz', full_name='vel.vz', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rz', full_name='vel.rz', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=150,
)

DESCRIPTOR.message_types_by_name['image'] = _IMAGE
DESCRIPTOR.message_types_by_name['depth_m'] = _DEPTH_M
DESCRIPTOR.message_types_by_name['vel'] = _VEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

image = _reflection.GeneratedProtocolMessageType('image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'image_pb2'
  # @@protoc_insertion_point(class_scope:image)
  })
_sym_db.RegisterMessage(image)

depth_m = _reflection.GeneratedProtocolMessageType('depth_m', (_message.Message,), {
  'DESCRIPTOR' : _DEPTH_M,
  '__module__' : 'image_pb2'
  # @@protoc_insertion_point(class_scope:depth_m)
  })
_sym_db.RegisterMessage(depth_m)

vel = _reflection.GeneratedProtocolMessageType('vel', (_message.Message,), {
  'DESCRIPTOR' : _VEL,
  '__module__' : 'image_pb2'
  # @@protoc_insertion_point(class_scope:vel)
  })
_sym_db.RegisterMessage(vel)


# @@protoc_insertion_point(module_scope)
